application: copy-editor
version: 1
runtime: python
api_version: 1

# Based on rietveld’s app.yaml file
# It's easy to program when you have a rockin' example to look up to

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/images/\1
  upload: static/(robots.txt|favicon.ico)

- url: /static
  static_dir: static

- url: .*
  script: main.py
